import { db } from "@/lib/db";
import { sendSms } from "@/lib/twilio";

/**
 * Request a witness confirmation for a pending activity.
 * Picks a random jar member (excluding the activity owner) and texts them
 * a one-tap confirmation link.
 */
export async function requestWitness(activityId: string): Promise<{
  witnessName: string;
  token: string;
} | null> {
  const activity = await db.activity.findUnique({
    where: { id: activityId },
    include: {
      user: true,
      jar: {
        include: {
          group: {
            include: {
              members: {
                include: { user: true },
                where: { userId: { not: undefined } },
              },
            },
          },
        },
      },
    },
  });

  if (!activity) return null;

  // Filter out the activity owner from potential witnesses
  const otherMembers = activity.jar.group.members.filter(
    (m) => m.userId !== activity.userId
  );

  if (otherMembers.length === 0) return null;

  // Pick a random witness
  const witnessIndex = Date.now() % otherMembers.length;
  const witnessMember = otherMembers[witnessIndex];

  // Create the witness record (token auto-generated by @default(cuid()))
  const witness = await db.witness.create({
    data: {
      activityId: activity.id,
      witnessId: witnessMember.userId,
    },
  });

  // Send confirmation SMS
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
  const confirmUrl = `${appUrl}/confirm/${witness.token}`;

  await sendSms(
    witnessMember.user.phone,
    `${activity.user.name} says they ${activity.description || "completed their daily goal"}. ` +
    `Can you confirm? Tap here: ${confirmUrl}`
  );

  return {
    witnessName: witnessMember.user.name,
    token: witness.token,
  };
}
